apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springboot-app-demo
  name: springboot-app-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-app-demo
  template:
    metadata:
      labels:
        app: springboot-app-demo
    spec:
      containers:
      - name: my-springboot-app
        image: 371699778015.dkr.ecr.us-east-1.amazonaws.com/springboot:latest
        ports:
        - containerPort: 8085
          name: http
          protocol: TCP
      imagePullSecrets:
      - name: regcred
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot-app-demo
    k8s-app: springboot-app-demo
  name: springboot-app-demo
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8085
  type: LoadBalancer
  selector:
    app: springboot-app-demo
